import { HighlightStyle } from '@codemirror/language';
import { EditorView } from '@codemirror/view';
import { tags } from '@lezer/highlight';

const monospace = 'Menlo, Monaco, Consolas, "Andale Mono", "Ubuntu Mono", "Courier New", monospace';

const dark = {
  foreground: '#d4d4d4',
  background: '#1e1e1e',
  cursor: '#c6c6c6',
  selection: '#094771',
  highlightLine: '#ffffff0f',
  gutterFg: '#858585',
  panelBg: '#252526',
  panelBorder: '#454545',
  panelShadow: 'rgba(0, 0, 0, 0.36)',
  inputBg: '#3c3c3c',
  inputBorder: '#3c3c3c',
  inputFocus: '#007fd4',
  inputFg: '#cccccc',
  buttonHoverBg: '#2a2d2e',
  toggleActiveBg: '#094771',
  toggleActiveBorder: '#007fd4',
  iconFg: '#cccccc',
  tooltipBg: '#252526',
  matchBracket: '#bad0f847',
  searchMatch: '#72a1ff59',
  searchMatchOutline: '#457dff',
  searchSelected: '#6199ff2f',
  selectionMatch: '#aafe661a',
  invalid: '#ff0000',
  keyword: '#569cd6',
  controlFlow: '#c586c0',
  function: '#dcdcaa',
  type: '#4ec9b0',
  tag: '#569cd6',
  operator: '#d4d4d4',
  regex: '#d16969',
  string: '#ce9178',
  name: '#9cdcfe',
  punctuation: '#d4d4d4',
  angleBracket: '#808080',
  templateBrace: '#569cd6',
  property: '#9cdcfe',
  atom: '#569cd6',
  number: '#b5cea8',
  comment: '#6a9955',
};

const light = {
  foreground: '#000000',
  background: '#ffffff',
  cursor: '#000000',
  selection: '#add6ff',
  highlightLine: '#0000000d',
  gutterFg: '#237893',
  panelBg: '#f3f3f3',
  panelBorder: '#c8c8c8',
  panelShadow: 'rgba(0, 0, 0, 0.16)',
  inputBg: '#ffffff',
  inputBorder: '#cecece',
  inputFocus: '#0090f1',
  inputFg: '#3b3b3b',
  buttonHoverBg: '#e8e8e8',
  toggleActiveBg: '#cce4f7',
  toggleActiveBorder: '#0090f1',
  iconFg: '#424242',
  tooltipBg: '#f3f3f3',
  matchBracket: '#0000004d',
  searchMatch: '#a8ac9433',
  searchMatchOutline: '#005a9e',
  searchSelected: '#a8ac9466',
  selectionMatch: '#a8ac9466',
  invalid: '#cd3131',
  keyword: '#0000ff',
  controlFlow: '#af00db',
  function: '#795e26',
  type: '#267f99',
  tag: '#800000',
  operator: '#000000',
  regex: '#811f3f',
  string: '#a31515',
  name: '#001080',
  punctuation: '#000000',
  angleBracket: '#808080',
  templateBrace: '#0000ff',
  property: '#001080',
  atom: '#0000ff',
  number: '#098658',
  comment: '#008000',
};

const buildEditorTheme = (c: typeof dark, isDark: boolean) =>
  EditorView.theme(
    {
      '&': {
        color: c.foreground,
        backgroundColor: c.background,
        height: '100%',
        width: '100%',
      },
      '.cm-scroller': {
        fontFamily: monospace,
        overflow: 'auto',
      },
      '.cm-content': {
        caretColor: c.cursor,
        paddingTop: '12px',
      },
      '.cm-cursor, .cm-dropCursor': { borderLeftColor: c.cursor },
      '&.cm-focused .cm-selectionBackground, .cm-selectionBackground, .cm-content ::selection': {
        backgroundColor: c.selection,
      },
      '.cm-panels': { backgroundColor: c.panelBg, color: c.foreground },
      '.cm-searchMatch': {
        backgroundColor: c.searchMatch,
        outline: `1px solid ${c.searchMatchOutline}`,
      },
      '.cm-searchMatch.cm-searchMatch-selected': {
        backgroundColor: c.searchSelected,
      },
      '.cm-activeLine': { backgroundColor: c.highlightLine },
      '.cm-selectionMatch': { backgroundColor: c.selectionMatch },
      '&.cm-focused .cm-matchingBracket, &.cm-focused .cm-nonmatchingBracket': {
        backgroundColor: c.matchBracket,
      },
      '.cm-gutters': {
        backgroundColor: c.background,
        color: c.gutterFg,
        border: 'none',
      },
      '.cm-activeLineGutter': { backgroundColor: c.highlightLine },
      '.cm-foldPlaceholder': {
        backgroundColor: 'transparent',
        border: 'none',
        color: c.gutterFg,
      },
      '.cm-tooltip': { backgroundColor: c.tooltipBg, color: c.foreground },
      '.cm-tooltip .cm-tooltip-arrow:before': {
        borderTopColor: 'transparent',
        borderBottomColor: 'transparent',
      },
      '.cm-tooltip .cm-tooltip-arrow:after': {
        borderTopColor: c.tooltipBg,
        borderBottomColor: c.tooltipBg,
      },

      '.cm-panels.cm-panels-top': {
        position: 'relative',
        borderBottom: 'none',
      },
      '.cm-panel.cm-search': {
        position: 'absolute',
        top: '4px',
        right: '20px',
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        gap: '2px',
        width: '380px',
        maxWidth: 'calc(100% - 40px)',
        padding: '4px 32px 4px 4px',
        backgroundColor: c.panelBg,
        color: c.foreground,
        border: `1px solid ${c.panelBorder}`,
        borderRadius: '4px',
        boxShadow: `0 2px 8px ${c.panelShadow}`,
        zIndex: '10',
      },
      '.cm-panel.cm-search br': {
        order: '2',
        flexBasis: '100%',
        height: '0',
        margin: '0',
        border: '0',
      },
      '.cm-panel.cm-search input[name="replace"]': { order: '3' },
      '.cm-panel.cm-search button[name="replace"], .cm-panel.cm-search button[name="replaceAll"]': { order: '3' },

      '.cm-panel.cm-search .cm-textfield': {
        flex: '1 1 auto',
        minWidth: '0',
        height: '24px',
        padding: '0 6px',
        margin: '0',
        fontSize: '12px',
        backgroundColor: c.inputBg,
        color: c.inputFg,
        border: `1px solid ${c.inputBorder}`,
        borderRadius: '2px',
        outline: 'none',
      },
      '.cm-panel.cm-search .cm-textfield:focus': {
        borderColor: c.inputFocus,
      },

      '.cm-panel.cm-search .cm-button': {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '24px',
        minWidth: '24px',
        padding: '0 6px',
        margin: '0',
        fontSize: '11px',
        lineHeight: '1',
        color: c.iconFg,
        backgroundColor: 'transparent',
        backgroundImage: 'none',
        border: '1px solid transparent',
        borderRadius: '3px',
        cursor: 'pointer',
        textTransform: 'none',
      },
      '.cm-panel.cm-search .cm-button:hover': {
        backgroundColor: c.buttonHoverBg,
      },
      '.cm-panel.cm-search .cm-button:focus-visible': {
        outline: `1px solid ${c.inputFocus}`,
        outlineOffset: '-1px',
      },
      '.cm-panel.cm-search .cm-button:active': {
        backgroundColor: c.buttonHoverBg,
      },

      '.cm-panel.cm-search button[name="next"]': { fontSize: '0', position: 'relative' },
      '.cm-panel.cm-search button[name="next"]::after': {
        content: '"↓"',
        fontSize: '14px',
        lineHeight: '1',
      },
      '.cm-panel.cm-search button[name="prev"]': { fontSize: '0', position: 'relative' },
      '.cm-panel.cm-search button[name="prev"]::after': {
        content: '"↑"',
        fontSize: '14px',
        lineHeight: '1',
      },
      '.cm-panel.cm-search button[name="select"]': { fontSize: '0', position: 'relative' },
      '.cm-panel.cm-search button[name="select"]::after': {
        content: '"≡"',
        fontSize: '14px',
        lineHeight: '1',
      },
      '.cm-panel.cm-search button[name="replace"]': { fontSize: '0', position: 'relative' },
      '.cm-panel.cm-search button[name="replace"]::after': {
        content: '"⇥"',
        fontSize: '14px',
        lineHeight: '1',
      },
      '.cm-panel.cm-search button[name="replaceAll"]': { fontSize: '0', position: 'relative' },
      '.cm-panel.cm-search button[name="replaceAll"]::after': {
        content: '"⇉"',
        fontSize: '14px',
        lineHeight: '1',
      },

      '.cm-panel.cm-search button[name="close"]': {
        position: 'absolute',
        top: '4px',
        right: '4px',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: '24px',
        height: '24px',
        padding: '0',
        margin: '0',
        backgroundColor: 'transparent',
        backgroundImage: 'none',
        border: '1px solid transparent',
        borderRadius: '3px',
        color: c.iconFg,
        fontSize: '14px',
        lineHeight: '1',
        cursor: 'pointer',
      },
      '.cm-panel.cm-search button[name="close"]:hover': {
        backgroundColor: c.buttonHoverBg,
      },

      '.cm-panel.cm-search label': {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '24px',
        minWidth: '24px',
        padding: '0 6px',
        fontSize: '0',
        color: c.iconFg,
        border: '1px solid transparent',
        borderRadius: '3px',
        cursor: 'pointer',
        userSelect: 'none',
      },
      '.cm-panel.cm-search label:hover': {
        backgroundColor: c.buttonHoverBg,
      },
      '.cm-panel.cm-search label input[type="checkbox"]': {
        position: 'absolute',
        opacity: '0',
        pointerEvents: 'none',
        margin: '0',
      },
      '.cm-panel.cm-search label:has(input:checked)': {
        backgroundColor: c.toggleActiveBg,
        borderColor: c.toggleActiveBorder,
      },
      '.cm-panel.cm-search label::before': {
        fontSize: '11px',
        fontFamily: monospace,
        fontWeight: '600',
        lineHeight: '1',
      },
      '.cm-panel.cm-search label:nth-of-type(1)::before': { content: '"Aa"' },
      '.cm-panel.cm-search label:nth-of-type(2)::before': { content: '".*"' },
      '.cm-panel.cm-search label:nth-of-type(3)::before': { content: '"\\\\b"' },
    },
    { dark: isDark },
  );

const buildHighlightStyle = (c: typeof dark) =>
  HighlightStyle.define([
    { tag: [tags.keyword, tags.operatorKeyword], color: c.keyword },
    { tag: [tags.controlKeyword, tags.moduleKeyword], color: c.controlFlow },
    { tag: [tags.name, tags.deleted, tags.character, tags.macroName], color: c.name },
    { tag: [tags.propertyName], color: c.property },
    { tag: [tags.variableName, tags.labelName], color: c.name },
    { tag: [tags.color, tags.constant(tags.name), tags.standard(tags.name)], color: c.atom },
    { tag: [tags.definition(tags.name)], color: c.foreground },
    {
      tag: [
        tags.typeName,
        tags.className,
        tags.number,
        tags.changed,
        tags.annotation,
        tags.modifier,
        tags.self,
        tags.namespace,
      ],
      color: c.type,
    },
    { tag: [tags.tagName], color: c.tag },
    { tag: [tags.function(tags.variableName), tags.function(tags.propertyName)], color: c.function },
    { tag: [tags.number], color: c.number },
    {
      tag: [tags.operator, tags.url, tags.escape, tags.regexp, tags.link, tags.special(tags.string)],
      color: c.operator,
    },
    { tag: [tags.regexp], color: c.regex },
    { tag: [tags.special(tags.string)], color: c.string },
    { tag: [tags.meta, tags.comment], color: c.comment },
    { tag: [tags.punctuation, tags.separator], color: c.punctuation },
    { tag: [tags.angleBracket], color: c.angleBracket },
    { tag: tags.special(tags.brace), color: c.templateBrace },
    { tag: tags.strong, fontWeight: 'bold' },
    { tag: tags.emphasis, fontStyle: 'italic' },
    { tag: tags.strikethrough, textDecoration: 'line-through' },
    { tag: tags.link, color: c.comment, textDecoration: 'underline' },
    { tag: tags.heading, fontWeight: 'bold', color: c.name },
    { tag: [tags.atom, tags.bool, tags.special(tags.variableName)], color: c.atom },
    { tag: [tags.processingInstruction, tags.string, tags.inserted], color: c.string },
    { tag: tags.invalid, color: c.invalid },
  ]);

export const darkTheme = buildEditorTheme(dark, true);
export const lightTheme = buildEditorTheme(light, false);
export const darkHighlightStyle = buildHighlightStyle(dark);
export const lightHighlightStyle = buildHighlightStyle(light);
